/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.service.base;

import com.liferay.amf.model.RegistrationEvent;
import com.liferay.amf.service.RegistrationEventService;
import com.liferay.amf.service.RegistrationEventServiceUtil;
import com.liferay.amf.service.persistence.LoginPersistence;
import com.liferay.amf.service.persistence.RegistrationEventPersistence;
import com.liferay.amf.service.persistence.RegistrationPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the registration event remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.amf.service.impl.RegistrationEventServiceImpl}.
 * </p>
 *
 * @author Bruno Queiroz
 * @see com.liferay.amf.service.impl.RegistrationEventServiceImpl
 * @generated
 */
public abstract class RegistrationEventServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, RegistrationEventService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RegistrationEventService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>RegistrationEventServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RegistrationEventService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		registrationEventService = (RegistrationEventService)aopProxy;

		_setServiceUtilService(registrationEventService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RegistrationEventService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RegistrationEvent.class;
	}

	protected String getModelClassName() {
		return RegistrationEvent.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				registrationEventPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		RegistrationEventService registrationEventService) {

		try {
			Field field = RegistrationEventServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, registrationEventService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected LoginPersistence loginPersistence;

	@Reference
	protected RegistrationPersistence registrationPersistence;

	@Reference
	protected com.liferay.amf.service.RegistrationEventLocalService
		registrationEventLocalService;

	protected RegistrationEventService registrationEventService;

	@Reference
	protected RegistrationEventPersistence registrationEventPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

}