/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Login service. Represents a row in the &quot;Registration_Login&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.amf.model.impl.LoginModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.amf.model.impl.LoginImpl</code>.
 * </p>
 *
 * @author Bruno Queiroz
 * @see Login
 * @generated
 */
@ProviderType
public interface LoginModel extends BaseModel<Login>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a login model instance should use the {@link Login} interface instead.
	 */

	/**
	 * Returns the primary key of this login.
	 *
	 * @return the primary key of this login
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this login.
	 *
	 * @param primaryKey the primary key of this login
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the login ID of this login.
	 *
	 * @return the login ID of this login
	 */
	public long getLoginId();

	/**
	 * Sets the login ID of this login.
	 *
	 * @param loginId the login ID of this login
	 */
	public void setLoginId(long loginId);

	/**
	 * Returns the group ID of this login.
	 *
	 * @return the group ID of this login
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this login.
	 *
	 * @param groupId the group ID of this login
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this login.
	 *
	 * @return the company ID of this login
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this login.
	 *
	 * @param companyId the company ID of this login
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this login.
	 *
	 * @return the user ID of this login
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this login.
	 *
	 * @param userId the user ID of this login
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this login.
	 *
	 * @return the user uuid of this login
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this login.
	 *
	 * @param userUuid the user uuid of this login
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this login.
	 *
	 * @return the create date of this login
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this login.
	 *
	 * @param createDate the create date of this login
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this login.
	 *
	 * @return the modified date of this login
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this login.
	 *
	 * @param modifiedDate the modified date of this login
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email address of this login.
	 *
	 * @return the email address of this login
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this login.
	 *
	 * @param emailAddress the email address of this login
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the password of this login.
	 *
	 * @return the password of this login
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this login.
	 *
	 * @param password the password of this login
	 */
	public void setPassword(String password);

}