/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RegistrationEvent service. Represents a row in the &quot;Registration_RegistrationEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.amf.model.impl.RegistrationEventModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.amf.model.impl.RegistrationEventImpl</code>.
 * </p>
 *
 * @author Bruno Queiroz
 * @see RegistrationEvent
 * @generated
 */
@ProviderType
public interface RegistrationEventModel
	extends BaseModel<RegistrationEvent>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a registration event model instance should use the {@link RegistrationEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this registration event.
	 *
	 * @return the primary key of this registration event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this registration event.
	 *
	 * @param primaryKey the primary key of this registration event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the registration event ID of this registration event.
	 *
	 * @return the registration event ID of this registration event
	 */
	public long getRegistrationEventId();

	/**
	 * Sets the registration event ID of this registration event.
	 *
	 * @param registrationEventId the registration event ID of this registration event
	 */
	public void setRegistrationEventId(long registrationEventId);

	/**
	 * Returns the group ID of this registration event.
	 *
	 * @return the group ID of this registration event
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this registration event.
	 *
	 * @param groupId the group ID of this registration event
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this registration event.
	 *
	 * @return the company ID of this registration event
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this registration event.
	 *
	 * @param companyId the company ID of this registration event
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this registration event.
	 *
	 * @return the user ID of this registration event
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this registration event.
	 *
	 * @param userId the user ID of this registration event
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this registration event.
	 *
	 * @return the user uuid of this registration event
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this registration event.
	 *
	 * @param userUuid the user uuid of this registration event
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this registration event.
	 *
	 * @return the user name of this registration event
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this registration event.
	 *
	 * @param userName the user name of this registration event
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this registration event.
	 *
	 * @return the create date of this registration event
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this registration event.
	 *
	 * @param createDate the create date of this registration event
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this registration event.
	 *
	 * @return the modified date of this registration event
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this registration event.
	 *
	 * @param modifiedDate the modified date of this registration event
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the event type of this registration event.
	 *
	 * @return the event type of this registration event
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this registration event.
	 *
	 * @param eventType the event type of this registration event
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the ip address of this registration event.
	 *
	 * @return the ip address of this registration event
	 */
	@AutoEscape
	public String getIpAddress();

	/**
	 * Sets the ip address of this registration event.
	 *
	 * @param ipAddress the ip address of this registration event
	 */
	public void setIpAddress(String ipAddress);

}